import { expect, test } from "@playwright/test";

test("design system searchable picker searches accents and selects with keyboard", { tag: "@webkit" }, async ({ page }) => {
  await page.goto("/packages/design-system/index.html");
  const trigger = page.getByRole("button", { name: "Find option", exact: true });
  await trigger.click();
  const search = page.getByRole("searchbox", { name: "Search options" });
  await expect(search).toBeFocused();
  await search.fill("CODEX cafe");
  await expect(page.locator(".ui-search-picker-choice")).toHaveCount(1);
  await expect(page.locator(".ui-search-picker-choice")).toContainText("Option 000");
  await search.fill("missing option");
  await expect(page.getByText("No options found", { exact: true })).toBeVisible();
  await search.fill("OPTION 099");
  await expect(page.locator(".ui-search-picker-choice")).toHaveCount(1);
  await search.press("ArrowDown");
  await page.keyboard.press("Enter");
  await expect(trigger).toBeFocused();
  await expect(page.locator(".ui-search-picker")).toHaveCount(0);
  await expect(page.getByText("Selected: Option 099", { exact: true })).toBeVisible();
});

test("design system searchable picker stays within narrow dialog and Escape closes first", { tag: "@webkit" }, async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 640 });
  await page.goto("/packages/design-system/index.html");
  await page.getByRole("button", { name: "Search in dialog", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Search example", exact: true });
  const trigger = dialog.getByRole("button", { name: "Find option", exact: true });
  await trigger.click();
  const picker = dialog.locator(".ui-search-picker");
  await expect(picker).toBeVisible();
  const box = await picker.boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width).toBeLessThanOrEqual(360);
  expect(box!.y + box!.height).toBeLessThanOrEqual(640);
  await page.getByRole("searchbox").press("Tab");
  await expect(picker).toBeVisible();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Favorite Option 000", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Refresh options", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(page.getByLabel("Show additional options", { exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(picker).toHaveCount(0);
  await expect(dialog).toBeVisible();
  await expect(trigger).toBeFocused();
  await trigger.click();
  await dialog.locator(".ui-search-picker-choice", { hasText: "Option 003" }).click();
  await expect(dialog.getByText("Selected: Option 003", { exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
});
