import { expect, test } from "@playwright/test";

test("design system mantém seleção, foco, validação e erro no diálogo", async ({ page }) => {
  await page.goto("/design-system.html");
  const open = page.getByRole("button", { name: "Configurar agente", exact: true });
  await open.click();
  const dialog = page.getByRole("dialog");
  const name = dialog.getByLabel("Nome do agente", { exact: true });
  await expect(name).toBeFocused();
  await dialog.getByRole("button", { name: "Salvar", exact: true }).click();
  await expect(dialog).toBeVisible();
  await expect(name).toBeFocused();
  await name.fill("Revisor");
  const provider = dialog.getByLabel("Provider", { exact: true });
  await provider.click();
  await expect(provider).toHaveAttribute("aria-expanded", "true");
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
  await expect(provider).toHaveAttribute("aria-expanded", "false");
  await provider.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Enter");
  await expect(provider).toHaveText("Codex");
  await expect(provider).toBeFocused();
  await dialog.getByLabel("Simular erro ao salvar").check();
  const save = dialog.getByRole("button", { name: "Salvar", exact: true });
  await save.focus();
  await page.keyboard.press("Tab");
  await expect(name).toBeFocused();
  await save.click();
  await expect(save).toBeDisabled();
  await expect(dialog.getByRole("alert")).toContainText("Não foi possível salvar");
  await expect(name).toHaveValue("Revisor");
  await dialog.getByLabel("Simular erro ao salvar").uncheck();
  await save.click();
  await expect(dialog).toBeHidden();
  await expect(open).toBeFocused();
  await page.setViewportSize({ width: 390, height: 640 });
  await open.click();
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  await page.keyboard.press("Escape");
  await expect(dialog).toBeHidden();
});
